Args = --initialize-at-build-time=org.apache.logging.log4j \
       --initialize-at-build-time=org.apache.logging.slf4j \
       --initialize-at-run-time=org.apache.logging.log4j.core.pattern.JAnsiTextRenderer
